spring:
  application:
    name: loanapi
  datasource:
    url: jdbc:h2:mem:loan_api
    driver-class-name: org.h2.Driver
    username: safa
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 8080

logging:
  level:
    web: debug
    security: debug

allowedNumberOfInstallments: 3,6,9,12,24
debug: true